### ISSUE TITLE
Files bundle

### ISSUE THREAD

**Issue by surendra-sketch** [ashukumar2001/webdev#1]
Hello Ashu how to bundle more than two HTML file. If you have any idea then please answer me. Thanks

**Comment by ashukumar2001** [comment]
Did you mean 2 html file in one repository?

**Comment by surendra-sketch** [comment]
No ,exact not that of my mean, just wanted to combine/merge to or more than
2 HTML files into a single HTML file ,any how. Hope that you get it.

**Comment by surendra-sketch** [comment]
Hello Ashu!
Okay so let's look my problem, acutlly I created more than 2 HTML file and
now having desired to combine all of them into a single HTML file that all
because of I Included links for move another file what I created in a
sequence way but aal those links working only in my editor or device ,but
when I tried to forward a single HTML file to someone in hope that he/she
would move another file because I have contacted all of them by just link
tag , but my idea not turn into the reality and I found that after one file
execute the next file doesn't excute into the others browser.and they find
it as blank page .


Please help me if it is possible , and know that may be it's not good
manner to explain in so long way , and thanks in advance .
